---
- hosts: all
  become: yes
  tasks:
  - name: i this tasks , i want to installl tree
    apt: 
       name: tree
       state: present

  - name: in this tasks, i want to install git 
    apt:
       name: git 
       state: present
  - name: in this tasks, i want to install wget
    apt: 
       name: wget
       state: present